# Generated by Django 3.1.3 on 2020-11-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('document', models.FileField(default='', upload_to='Homepage/files')),
                ('title', models.CharField(max_length=50, null=True)),
                ('semester', models.IntegerField(max_length=10, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('Branch', models.CharField(max_length=50, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
