# Generated by Django 3.1.3 on 2020-12-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_auto_20201220_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file_type',
            field=models.FileField(null=True, upload_to='Notes/pdfs'),
        ),
    ]
